import Footer from "@/components/common/Footer";
import MobileNavBar from "@/components/common/MobileNavBar";
import NavBar from "@/components/common/NavBar";
import ScrollToTop from "@/components/common/ScrollToTop";
import { ThemeProvider } from "@/components/common/ThemeProvider";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Daawat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          <MobileNavBar />
          <ScrollToTop />
          <main className="flex-grow">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
